# Generated by Django 4.1.3 on 2025-01-23 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_workflows', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_operator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='ticket_operator',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_state', verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='ticket_operator',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tickets.ticket', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='ticket_log',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='ticket_log',
            name='transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_transition', verbose_name='流转'),
        ),
        migrations.AddField(
            model_name='ticket_field',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_field', verbose_name='字段'),
        ),
        migrations.AddField(
            model_name='ticket_field',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.ticket', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_state', verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_workflow', verbose_name='工作流'),
        ),
    ]
