# Generated by Django 4.1.3 on 2025-01-23 05:34

from django.db import migrations, models
import django.db.models.deletion
from menu.models import Menu
from common.Constant import MENU


def init_data(apps, schema_editor):
    def create_data(data, parent=None):
        for name, value in data.items():
            obj, _ = Menu.objects.update_or_create(
                defaults={
                    "order": value.get("order"),
                    "parent": parent,
                    "urls": value.get("urls", None),
                    "index": value.get("index", None)
                },
                name=name
            )
            if value.get("leaf"):
                create_data(value.get("leaf"), obj)
    try:
        create_data(MENU.TREE)
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜单名')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('index', models.CharField(blank=True, max_length=50, null=True, verbose_name='url索引')),
                ('urls', models.CharField(blank=True, max_length=1024, null=True, verbose_name='包含url')),
                ('workflow_id', models.IntegerField(blank=True, null=True, verbose_name='工作流id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='menu.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单信息',
                'verbose_name_plural': '菜单信息',
                'db_table': 'ops_menu',
            },
        ),
        migrations.RunPython(init_data)
    ]
