# Generated by Django 4.1.3 on 2025-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.IntegerField(choices=[(1, 'Reset PassWord'), (2, 'Check Ticket')], default=1, verbose_name='任务类型')),
                ('reference_id', models.BigIntegerField(default=None, null=True, verbose_name='关联对象ID')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
            ],
            options={
                'verbose_name': '个人任务',
                'verbose_name_plural': '个人任务',
                'db_table': 'ops_todo_tasks',
            },
        ),
    ]
