# Generated by Django 4.1.3 on 2025-01-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('field_type', models.IntegerField(choices=[(1, '字符串'), (2, '整型'), (3, '浮点型'), (4, '布尔'), (5, '日期'), (6, '日期时间'), (7, '范围日期'), (8, '文本域'), (9, '单选框'), (10, '下拉列表'), (11, '外键'), (12, '多选框'), (13, '多选下拉'), (14, '多选外键')], default=1, verbose_name='字段类型')),
                ('field_key', models.CharField(help_text='字段类型请尽量特殊，避免与系统中关键字冲突', max_length=50, verbose_name='字段标识')),
                ('name', models.CharField(max_length=50, verbose_name='字段名称')),
                ('order_id', models.IntegerField(default=0, verbose_name='排序')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('displayed', models.BooleanField(default=False, verbose_name='是否展示')),
                ('default_value', models.CharField(blank=True, help_text='前端展示时，可以将此内容作为表单中的该字段的默认值', max_length=100, null=True, verbose_name='默认值')),
                ('field_placeholder', models.TextField(blank=True, default='', help_text='文本域类型字段前端显示时可以将此内容作为字段的placeholder', null=True, verbose_name='文本域模板')),
                ('field_choice', models.CharField(blank=True, default='{}', help_text="radio,checkbox,select,multiselect类型可供选择的选项，格式为json如:{'1':'中国', '2':'美国'},注意数字也需要引号", max_length=255, null=True, verbose_name='radio、checkbox、select的选项')),
                ('special_url', models.CharField(blank=True, default=None, help_text="指定调用该url获取数据，<>中为其他字段的key，需要前端替换<>中的值，例如'/user/<test_id>'", max_length=100, null=True, verbose_name='获取数据的url')),
            ],
            options={
                'verbose_name': '工作流自定义字段',
                'verbose_name_plural': '工作流自定义字段',
                'db_table': 'ops_custom_filed',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Custom_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('order_id', models.IntegerField(default=1, verbose_name='状态顺序')),
                ('state_type', models.IntegerField(choices=[(0, '初始状态'), (1, '普通状态'), (2, '结束状态')], default=0, verbose_name='状态类型')),
                ('enable_retreat', models.BooleanField(default=False, help_text='开启后允许工单创建人在此状态直接撤回工单到初始状态', verbose_name='允许撤回')),
                ('participant_type', models.IntegerField(choices=[(0, '无'), (1, '个人'), (2, '角色'), (3, '自定义字段用户')], default=0, verbose_name='参与者类型')),
                ('participant', models.CharField(blank=True, default='[]', help_text='可以为userid/多个userid(以,隔开)/角色id/多个角色id(以,隔开)', max_length=1000, null=True, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '工作流状态',
                'verbose_name_plural': '工作流状态',
                'db_table': 'ops_custom_status',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Custom_Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='流转名称')),
                ('trans_type', models.IntegerField(choices=[(1, '只需要单个处理'), (2, '需要全部处理')], default=1, verbose_name='处理方式')),
                ('alert_enable', models.BooleanField(default=False, verbose_name='点击弹窗提示')),
                ('alert_text', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='弹窗内容')),
            ],
            options={
                'verbose_name': '工作流流转',
                'verbose_name_plural': '工作流流转',
                'db_table': 'ops_custom_transition',
            },
        ),
        migrations.CreateModel(
            name='Custom_Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '发送消息给后续人员'), (2, '自定义')], default=1, verbose_name='触发器类型')),
                ('order', models.IntegerField(default=1, verbose_name='触发器顺序')),
            ],
            options={
                'verbose_name': '工作流流转触发器',
                'verbose_name_plural': '工作流流转触发器',
                'db_table': 'ops_custom_trigger',
            },
        ),
        migrations.CreateModel(
            name='Custom_Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(max_length=1024, verbose_name='描述')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
            ],
            options={
                'verbose_name': '自定义工作流',
                'verbose_name_plural': '自定义工作流',
                'db_table': 'ops_custom_workflow',
            },
        ),
        migrations.CreateModel(
            name='Status_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_field')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_state')),
            ],
            options={
                'verbose_name': '状态字段关联表',
                'verbose_name_plural': '状态字段关联表',
                'db_table': 'ops_custom_status_fields',
            },
        ),
    ]
