# Generated by Django 4.1.3 on 2025-01-23 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_workflow',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='custom_trigger',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='custom_workflows.custom_transition'),
        ),
        migrations.AddField(
            model_name='custom_transition',
            name='dest_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_state', to='custom_workflows.custom_state', verbose_name='目的状态'),
        ),
        migrations.AddField(
            model_name='custom_transition',
            name='source_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_state', to='custom_workflows.custom_state', verbose_name='源状态'),
        ),
        migrations.AddField(
            model_name='custom_transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_workflows.custom_workflow', verbose_name='工作流'),
        ),
        migrations.AddField(
            model_name='custom_state',
            name='fields',
            field=models.ManyToManyField(blank=True, through='custom_workflows.Status_Field', to='custom_workflows.custom_field', verbose_name='可编辑字段'),
        ),
        migrations.AddField(
            model_name='custom_state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_list', to='custom_workflows.custom_workflow', verbose_name='工作流'),
        ),
        migrations.AddField(
            model_name='custom_field',
            name='foreign_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='外键类型'),
        ),
        migrations.AddField(
            model_name='custom_field',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_list', to='custom_workflows.custom_workflow', verbose_name='工作流'),
        ),
        migrations.AlterUniqueTogether(
            name='custom_state',
            unique_together={('workflow', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='custom_field',
            unique_together={('workflow', 'field_key')},
        ),
    ]
